default.tmux.bin_path = "/opt/tmux/bin/tmux"
default.tmux.checksum = "795f4b4446b0ea968b9201c25e8c1ef8a6ade710ebca4657dd879c35916ad362"
default.tmux.configure_options = %w[ --prefix=/opt/tmux ]
default.tmux.install_method = "source"
default.tmux.symlink_group = "root"
default.tmux.symlink_path = "/usr/bin/tmux"
default.tmux.symlink_user = "root"
default.tmux.user_conf_group = "root"
default.tmux.user_conf_path = "/root/.tmux.conf"
default.tmux.user_conf_user = "root"
default.tmux.version = "2.0"
