default.tmux.bin_path = "/opt/tmux/bin/tmux"
default.tmux.checksum = "977871e7433fe054928d86477382bd5f6794dc3d"
default.tmux.configure_options = %w[ --prefix=/opt/tmux ]
default.tmux.install_method = "source"
default.tmux.symlink_group = "root"
default.tmux.symlink_path = "/usr/bin/tmux"
default.tmux.symlink_user = "root"
default.tmux.user_conf_group = "root"
default.tmux.user_conf_path = "/root/.tmux.conf"
default.tmux.user_conf_user = "root"
default.tmux.version = "2.0"
